package golangci

import (
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"sort"
	"strconv"

	"gopkg.in/yaml.v3"

	"github.com/kapetan-io/tiger/internal/rules"
)

// Generate derives the baseline golangci-lint configuration from the
// registry's auto rules, with module filled into the module-dependent
// settings. The result passes Verify unchanged, by construction: the enable
// lists and settings are built from the same table Verify audits.
func Generate(module string) ([]byte, error) {
	document := map[string]any{
		"version": "2",
		rules.SectionLinters: map[string]any{
			"default": "standard",
			"enable":  enabledLinters(rules.SectionLinters),
		},
		rules.SectionFormatters: map[string]any{
			"enable": enabledLinters(rules.SectionFormatters),
		},
		// A finding you cannot see is a finding you will not fix.
		"issues": map[string]any{
			"max-issues-per-linter": 0,
			"max-same-issues":       0,
		},
	}
	for _, rule := range rules.AutoRules() {
		for _, setting := range rule.Settings {
			insert(document, setting.Path, rules.SubstituteModule(setting.Want, module))
		}
	}
	root := encode(document)
	root.HeadComment = "Generated by tiger golangci --init from the tiger rule registry.\n" +
		"Every linter and setting below enforces an auto rule of the Tiger Go\n" +
		"Specification; tiger golangci audits this file against that baseline."
	return yaml.Marshal(root)
}

// Init writes the generated baseline into dir, refusing to touch an
// existing configuration. It returns the path written.
func Init(dir string) (string, error) {
	if existing, found := configPath(dir); found {
		return "", fmt.Errorf("%w: %s", ErrConfigExists, existing)
	}
	module, err := modulePath(dir)
	if err != nil {
		return "", err
	}
	generated, err := Generate(module)
	if err != nil {
		return "", err
	}
	path := filepath.Join(dir, configNames[0])
	if err := os.WriteFile(path, generated, 0o644); err != nil {
		return "", fmt.Errorf("writing %s: %w", path, err)
	}
	return path, nil
}

// enabledLinters collects the linters a section must enable, sorted,
// skipping the members of golangci-lint's standard default group.
func enabledLinters(section string) []any {
	seen := map[string]bool{}
	names := []string{}
	for _, rule := range rules.AutoRules() {
		if rule.Section != section || seen[rule.Linter] {
			continue
		}
		seen[rule.Linter] = true
		if section == rules.SectionLinters && rules.StandardLinter(rule.Linter) {
			continue
		}
		names = append(names, rule.Linter)
	}
	sort.Strings(names)
	listed := make([]any, len(names))
	for i, name := range names {
		listed[i] = name
	}
	return listed
}

// insert places a baseline fragment at path, creating nested maps on the
// way. Rules sharing a list-valued path (the revive rules of TS-N01, TS-N10,
// and TS-L07) merge their elements instead of overwriting each other, in
// registry order, so the generated list satisfies every contributing rule.
func insert(document map[string]any, path []string, fragment any) {
	current := document
	for _, key := range path[:len(path)-1] {
		next, found := current[key].(map[string]any)
		if !found {
			next = map[string]any{}
			current[key] = next
		}
		current = next
	}
	leaf := path[len(path)-1]
	held, heldSeq := current[leaf].([]any)
	incoming, incomingSeq := fragment.([]any)
	if heldSeq && incomingSeq {
		merged := slices.Clone(held)
		for _, element := range incoming {
			if !slices.ContainsFunc(merged, func(candidate any) bool {
				return reflect.DeepEqual(candidate, element)
			}) {
				merged = append(merged, element)
			}
		}
		current[leaf] = merged
		return
	}
	current[leaf] = fragment
}

// encodeTask pairs one fragment with the node the walk fills for it.
type encodeTask struct {
	fragment any
	node     *yaml.Node
}

// encode builds a yaml.Node tree with map keys sorted, so the generated
// document is byte-identical across runs — yaml.Marshal on plain maps would
// leak map iteration order into the output (constraint 4). The walk is an
// index-advancing worklist: nested fragments get empty child nodes filled
// on later passes.
func encode(fragment any) *yaml.Node {
	root := &yaml.Node{}
	work := []encodeTask{{fragment: fragment, node: root}}
	for i := 0; i < len(work); i++ {
		work = fillNode(work, i)
	}
	return root
}

// fillNode fills one task's node, appending child tasks for nested values.
func fillNode(work []encodeTask, i int) []encodeTask {
	node := work[i].node
	switch typed := work[i].fragment.(type) {
	case map[string]any:
		node.Kind, node.Tag = yaml.MappingNode, "!!map"
		for _, key := range slices.Sorted(maps.Keys(typed)) {
			child := &yaml.Node{}
			node.Content = append(node.Content,
				&yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: key}, child)
			work = append(work, encodeTask{fragment: typed[key], node: child})
		}
	case []any:
		node.Kind, node.Tag = yaml.SequenceNode, "!!seq"
		for _, element := range typed {
			child := &yaml.Node{}
			node.Content = append(node.Content, child)
			work = append(work, encodeTask{fragment: element, node: child})
		}
	case string:
		node.Kind, node.Tag, node.Value = yaml.ScalarNode, "!!str", typed
	case bool:
		node.Kind, node.Tag, node.Value = yaml.ScalarNode, "!!bool", strconv.FormatBool(typed)
	case int:
		node.Kind, node.Tag, node.Value = yaml.ScalarNode, "!!int", strconv.Itoa(typed)
	case float64:
		node.Kind, node.Tag = yaml.ScalarNode, "!!float"
		node.Value = strconv.FormatFloat(typed, 'f', 1, 64)
	default:
		node.Kind, node.Tag = yaml.ScalarNode, "!!str"
		node.Value = fmt.Sprintf("%v", work[i].fragment)
	}
	return work
}
