package golangci

import (
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"sort"
	"strconv"

	"gopkg.in/yaml.v3"

	"github.com/kapetan-io/tiger/internal/rules"
)

// Generate derives the baseline golangci-lint configuration from the
// registry's auto rules, with module filled into the module-dependent
// settings. The result passes Verify unchanged, by construction: the enable
// lists and settings are built from the same table Verify audits.
func Generate(module string) ([]byte, error) {
	document := map[string]any{
		"version": "2",
		rules.SectionLinters: map[string]any{
			"default": "standard",
			"enable":  enabledLinters(rules.SectionLinters),
		},
		rules.SectionFormatters: map[string]any{
			"enable": enabledLinters(rules.SectionFormatters),
		},
		// A finding you cannot see is a finding you will not fix.
		"issues": map[string]any{
			"max-issues-per-linter": 0,
			"max-same-issues":       0,
		},
	}
	for _, rule := range rules.AutoRules() {
		for _, setting := range rule.Settings {
			insert(document, setting.Path, rules.SubstituteModule(setting.Want, module))
		}
	}
	root := encode(document)
	root.HeadComment = "Generated by tiger golangci --init from the tiger rule registry.\n" +
		"Every linter and setting below enforces an auto rule of the Tiger Go\n" +
		"Specification; tiger golangci audits this file against that baseline."
	return yaml.Marshal(root)
}

// Init writes the generated baseline into dir, refusing to touch an
// existing configuration. It returns the path written.
func Init(dir string) (string, error) {
	if existing, found := configPath(dir); found {
		return "", fmt.Errorf("%w: %s", ErrConfigExists, existing)
	}
	module, err := modulePath(dir)
	if err != nil {
		return "", err
	}
	generated, err := Generate(module)
	if err != nil {
		return "", err
	}
	path := filepath.Join(dir, configNames[0])
	if err := os.WriteFile(path, generated, 0o644); err != nil {
		return "", fmt.Errorf("writing %s: %w", path, err)
	}
	return path, nil
}

// enabledLinters collects the linters a section must enable, sorted,
// skipping the members of golangci-lint's standard default group.
func enabledLinters(section string) []any {
	seen := map[string]bool{}
	names := []string{}
	for _, rule := range rules.AutoRules() {
		if rule.Section != section || seen[rule.Linter] {
			continue
		}
		seen[rule.Linter] = true
		if section == rules.SectionLinters && rules.StandardLinter(rule.Linter) {
			continue
		}
		names = append(names, rule.Linter)
	}
	sort.Strings(names)
	listed := make([]any, len(names))
	for i, name := range names {
		listed[i] = name
	}
	return listed
}

// insert places a baseline fragment at path, creating nested maps on the
// way. Rules sharing a list-valued path (the revive rules of TS-N01, TS-N10,
// and TS-L07) merge their elements instead of overwriting each other, in
// registry order, so the generated list satisfies every contributing rule.
func insert(document map[string]any, path []string, fragment any) {
	current := document
	for _, key := range path[:len(path)-1] {
		next, found := current[key].(map[string]any)
		if !found {
			next = map[string]any{}
			current[key] = next
		}
		current = next
	}
	leaf := path[len(path)-1]
	held, heldSeq := current[leaf].([]any)
	incoming, incomingSeq := fragment.([]any)
	if heldSeq && incomingSeq {
		merged := slices.Clone(held)
		for _, element := range incoming {
			if !slices.ContainsFunc(merged, func(candidate any) bool {
				return reflect.DeepEqual(candidate, element)
			}) {
				merged = append(merged, element)
			}
		}
		current[leaf] = merged
		return
	}
	current[leaf] = fragment
}

// encode builds a yaml.Node tree with map keys sorted, so the generated
// document is byte-identical across runs — yaml.Marshal on plain maps would
// leak map iteration order into the output (constraint 4).
func encode(fragment any) *yaml.Node {
	switch typed := fragment.(type) {
	case map[string]any:
		keys := make([]string, 0, len(typed))
		for key := range typed {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		node := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
		for _, key := range keys {
			node.Content = append(node.Content,
				&yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: key},
				encode(typed[key]))
		}
		return node
	case []any:
		node := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
		for _, element := range typed {
			node.Content = append(node.Content, encode(element))
		}
		return node
	case string:
		return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: typed}
	case bool:
		return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: strconv.FormatBool(typed)}
	case int:
		return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!int", Value: strconv.Itoa(typed)}
	case float64:
		return &yaml.Node{
			Kind: yaml.ScalarNode, Tag: "!!float",
			Value: strconv.FormatFloat(typed, 'f', 1, 64),
		}
	default:
		return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: fmt.Sprintf("%v", typed)}
	}
}
